name: Station Maintenance Work Request
description: Report and track facility issues/maintenance.
title: "[Station] <Brief description of the issue>"
labels: ["maintenance", "station"]

body:

- type: markdown
  attributes:
    value: |
      Thank you for submitting a maintenance request. Please fill out the details below to help us address your issue promptly.

- type: input
  id: requester-name
  attributes:
    label: Requester Name
    description: Your full name
  validations:
    required: true

# - type: input
#   id: contact-information
#   attributes:
#     label: Contact Information (Phone/Email)
#     description: How can we best reach you?
#   validations:
#     required: true

- type: dropdown
  id: priority
  attributes:
    label: Priority Level
    description: How urgent is this issue?
    options:
      - Low
      - Medium
      - High
      - Urgent
  validations:
    required: true

- type: dropdown
  id: building
  attributes:
    label: Station
    description: Select the station where the issue is.
    options:
      - Station 1
      - Station 2
      - Both
  validations:
    required: true

- type: dropdown
  id: request-type
  attributes:
    label: Type of Request
    description: What kind of work is needed?
    options:
      - General Maintenance
      - Infrastructure (plumbing, electrical, HVAC)
      - Technology (computers, internet, station radio)
      - Consumables purchase request (paper towel, soap, etc)
      - Doors & Bay Doors
      - Exterior
      - Cleaning/Recurring (mowing, etc)
      - Other
  validations:
    required: true

- type: input
  id: room
  attributes:
    label: Specific location
    description: Where exactly is the issue? (small bathroom, engine bay, kitchen, etc)

- type: input
  id: parts
  attributes:
    label: Will materials need to be bought?
    description: If so, include a rough estimate as to the cost to the department if you know. 

- type: textarea
  id: detailed-description
  attributes:
    label: Detailed Description of the Issue
    description: Please provide a thorough explanation.
  validations:
    required: true

- type: textarea
  id: supporting-documents
  attributes:
    label: Supporting Pictures or Documents (optional)
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in. You can also attach them after the issue is created. 
