name: Vehicle Maintenance Work Request
description: Report and track issues/maintenance work for department vehicles.
title: "[Vehicle] <Brief description of the issue>"
labels: ["maintenance", "vehicle"]

body:

- type: markdown
  attributes:
    value: |
      Thank you for submitting a maintenance request. Please fill out the details below to help us address your issue promptly.

- type: input
  id: requester-name
  attributes:
    label: Requester Name
    description: Your name
  validations:
    required: true

# - type: input
#   id: contact-information
#   attributes:
#     label: Contact Information (Phone/Email)
#     description: How can we best reach you?
#   validations:
#     required: true

- type: dropdown
  id: priority
  attributes:
    label: Priority Level
    description: How urgent is this issue?
    options:
      - Low
      - Medium
      - High
      - Urgent
  validations:
    required: true

- type: dropdown
  id: vehicle
  attributes:
    label: Vehicle
    description: Select the vehicle with the issue.
    options:
      - Rescue 1 (station 2)
      - Engine 1 (station 1)
      - Engine 2 (station 1)
      - Engine 3 (station 2)
      - Engine 4 (station 2)
      - Emergency Response Trailer (station 2)
      - QRV
  validations:
    required: true

- type: dropdown
  id: request-type
  attributes:
    label: Type of Request
    description: What kind of work is needed?
    options:
      - Vehicle Engine/Handling (steering, wheels, etc)
      - Lights, Sirens, Horns
      - Radio/Communications
      - Engine Pump
      - Firefighting Equipment (hoses, SCBAs, etc)
      - Rescue/Extrication Equipment
      - Vehicle Equipment (lights, tools, misc.)
      - Other
  validations:
    required: true

- type: input
  id: location
  attributes:
    label: Specific location
    description: Where exactly is the issue? (compartment 5, rear seat, passenger side door, etc)

- type: input
  id: parts
  attributes:
    label: Will parts need to be bought?
    description: If so, include a rough estimate as to the cost to the department if you know. 

- type: textarea
  id: detailed-description
  attributes:
    label: Detailed Description of the Issue
    description: Please provide a thorough explanation.
  validations:
    required: true

- type: textarea
  id: supporting-documents
  attributes:
    label: Supporting Pictures or Documents (optional)
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in. You can also attach them after the issue is created. 
